# Generated by Django 5.1.4 on 2025-01-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('date_embauche', models.DateField()),
                ('adresse', models.TextField()),
                ('historique_professionnel', models.TextField(blank=True, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('formations', models.TextField(blank=True, null=True)),
                ('solde_conge', models.PositiveIntegerField(default=0)),
                ('droits_conge', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('code_service', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_contrat', models.CharField(max_length=100)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrats à durée indéterminée'), ('CDD', 'contrats à durée déterminée'), ('STAGE', 'stage')], max_length=20)),
                ('type_salaire', models.CharField(choices=[('mensuel', 'Mensuel'), ('quotidien', 'Quotidien')], default='mensuel', max_length=10)),
                ('montant_salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_conge', models.CharField(max_length=10, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé Annuel'), ('MALADIE', 'Congé Maladie'), ('MATERNITE', 'Congé de Maternité'), ('PATERNITE', 'Congé de Paternité'), ('SANS_SOLDE', 'Congé Sans Solde'), ('AUTRE', 'Autre')], max_length=20)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluation', models.DateField()),
                ('objecttifs', models.TextField()),
                ('competances', models.TextField()),
                ('performance_globale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.service'),
        ),
    ]
