# Generated by Django 5.1.4 on 2025-01-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nb_absence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
