# Generated by Django 5.1.4 on 2025-01-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_employe_nb_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='nb_absence',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='projectapp.employe')),
            ],
        ),
    ]
