# Generated by Django 5.1.4 on 2025-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_remove_employe_nb_absence_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='nb_absence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
