# Generated by Django 5.1.4 on 2025-01-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_employe_nb_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
