# Generated by Django 5.1.4 on 2025-01-15 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_candidature_offreemploi_absence_est_absent_entretien_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='date_candidature',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidature',
            name='nom_candidat',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='notes',
        ),
        migrations.AddField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='projectapp.offreemploi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entretien',
            name='candidature',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='projectapp.candidature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entretien',
            name='lieu',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entretien',
            name='remarques',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
