# Generated by Django 5.1.4 on 2025-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_remove_candidature_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='adresse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
