# Generated by Django 5.1.4 on 2025-01-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_employe_nb_massrouf_alter_entretien_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='nbr_massrouf',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
